### ISSUE TITLE
Remove generation messages?

### ISSUE THREAD

**Issue by LoneWolfHT** [HybridDog/nyanland#2]
![image](https://user-images.githubusercontent.com/28972859/32255596-4b8b386a-be66-11e7-91ca-61b3d627b51a.png)
I'd like to use this on a public server but the messages would spam the chat.

**Comment by HybridDog** [comment]
You're right, the messages are (or should) only be displayed in singleplayer mode: https://github.com/HybridDog/nyanland/blob/master/init.lua#L7

EDIT: Now they're configurable, disabled by default.
